version: '3.4'


services:
  postwa:
    env_file:
      - .env
    image: postwa
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production    
    ports:
      - 3000:3000
    links: #here
      - mongodb
  mongodb:
    image: mongo:4.4.6
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

